version: "3"

services:
  observer:
    build: ./push-server
    command: nodemon server.js
    ports:
    - "8123:8123"
    volumes:
    - ./push-server:/usr/src/push-server
    depends_on:
    - db
    environment:
    - DATABASE_HOST=db
  db:
    build: ./database
    # volumes:
    # - "./data/pn.sql:/docker-entrypoint-initdb.d/000.sql"
  app:
    build: ./app
    command: nodemon --ext js,html,css server.js
    ports:
    - "8124:8124"
    volumes:
    - ./app:/usr/src/app
