version: "3"

services:
  observer:
    build: ./push-server
    command: nodemon server.js
    ports:
    - "${PUSH_SERVER_PORT}:${PUSH_SERVER_PORT}"
    volumes:
    - ./push-server:/usr/src/push-server
    depends_on:
    - db
    environment:
    - DB_HOST=db
    - DB_NAME=${MYSQL_DATABASE}
    - DB_USER=root
    - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - PUSH_SERVER_PORT
  db:
    build: ./database
    environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
  app:
    build: ./app
    command: nodemon --ext js,html,css server.js
    ports:
    - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
    volumes:
    - ./app:/usr/src/app
    environment:
    - APP_SERVER_PORT
    - APP_SERVER_HOST
