version: "3"

services:
  observer:
    build: ./push-server
    command: nodemon --ext html,js,css server.js
    ports:
    - "${PUSH_SERVER_PORT}:${PUSH_SERVER_PORT}"
    volumes:
    - ~/.aws:/root/.aws
    depends_on:
    - db
    environment:
    - DB_HOST=db
    - DB_NAME=${MYSQL_DATABASE}
    - DB_USER=root
    - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - PUSH_SERVER_HOST
    - PUSH_SERVER_PORT
    - PUSH_SERVER_VAPID_PUBLIC_KEY
    - AWS_PROFILE
  db:
    build: ./store
    environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
  app:
    build: ./app
    command: node src/server/start.js
    ports:
    - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
    environment:
    - APP_SERVER_HOST
    - APP_SERVER_PORT
    - PUSH_API_URL
    - PUSH_SERVER_VAPID_PUBLIC_KEY